name: chanzhanggui_syd
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.
  flutter_screenutil: ^1.0.2
  cupertino_icons: ^0.1.2 # 图标资源
  dio: ^2.1.10 # http请求
  cookie_jar: ^1.0.1 # cookie 管理
  intl: ^0.15.8 # 本地化格式 日期
  flutter_datetime_picker: ^1.2.5 # 日期选取
  city_pickers: ^0.1.30 # 城市选取
  fluttertoast: ^3.1.0 # toast
  easy_dialog: ^1.0.5 # 对话框
  flutter_easyrefresh: ^1.2.7 # 下拉刷新
  permission_handler: ^3.2.2 # 权限申请
  path_provider: ^1.2.0 # 查询常用位置
  back_button_interceptor: ^4.0.7 # 返回按钮
  keyboard_visibility: ^0.5.6 # 键盘监听
  extended_image: ^0.7.1 # ^0.5.6 # 图片扩展 圆角 缓存
  flutter_picker: ^1.0.15 # 选取器
  f_logs: ^1.2.0 # 日志
  sentry: ^2.2.0 # 错误收集平台
  flutter_swiper : ^1.1.6 #swiper 切换
# 数据
  shared_preferences: ^0.5.3+4 # 本地数据共享
  synchronized: ^2.1.0+1 # 异步锁
  flutter_secure_storage: ^3.2.1+1 # 本地缓存 kv
  flutter_redux: ^0.5.2 #

# bloc
  meta: ^1.1.6
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  equatable: ^0.3.0

# 路由
  fluro: ^1.5.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/images/
  - assets/images/icon/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
